### PR TITLE
Replace Highcharts with Plotly

### PR DESCRIPTION
**Pull request by arximboldi**
Plotly (https://plot.ly/javascript/) does not have the licensing
problems discussed in #53.  Furthermore, it has more features and plot
styles, which will be useful later, like in #36.

In this branch I tried to keep the styling similar to the one with
Highlights.  I made small changes, that I consider improvements, like
making the plot adapt automatically to the window size -- including on
resize.

An example of the new look of the reports can be seen here:

https://sinusoid.es/misc/nonius-example2-plotly.html

### CODE REVIEW

**Comment by rmartinho** [comment]
The build server cannot build this PR because the author is not whitelisted. A meatbag will have to look at it.

**This is an automated message.**

**Comment by rmartinho** [comment]
Thanks for this! I'll have a look during the weekend. I have no usable build slaves due to hardware issues so I'll have to check all compilers by hand :/

**Comment by arximboldi** [comment]
Just added a commit to always show the zero in the time dimension. I find this useful, because otherwise the graph is misleading w.r.t. the relative performance of the different results. The zooming in Plotly works quite well so it is easy to zoom in when this leads to the points being too close to eachother.

Here is an example:
https://sinusoid.es/misc/nonius-example1-plotly.html

**Comment by rmartinho** [comment]
Thanks for this. It's merged.

**Pull request merged**
