### PR TITLE
Benchmark parameters II (API improvements)

### PR DESCRIPTION
**Pull request by arximboldi**
This pull request tries to improve the parameters API. It is a continuation of #56. Following up on the discussion on that pull-request, I try here to make the parameters API more terse and robust. The last commit includes more details.

This branch also has a commit addressing #10. It could be extracted, but I just happened to do it in this branch.

### CODE REVIEW

**Comment by rmartinho** [comment]
The build server cannot build this PR because the author is not whitelisted. A meatbag will have to look at it.

**This is an automated message.**

**Comment by griwes** [comment]
I like this. :+1:

**Comment by ThePhD** [comment]
:tada: Cheers!

**Comment by rmartinho** [comment]
This looks nice. I'll probably only merge all this next month when I'm back from holiday, once I write docs  for it: #64.

**Comment by rmartinho** [comment]
Can you move the commit that addresses #10 out? There's some discussion to be had on that and it'd be better if it was done in a separate PR.

**Comment by arximboldi** [comment]
Done!

**Pull request merged**
