### PR TITLE
Fix example includes

### PR DESCRIPTION
**Pull request by gnzlbg**
As it was before one had to put the include/ and include/nonius
directories in the path.

Now one only has to put the include/ directory in the path.

### CODE REVIEW

**Comment by gnzlbg** [comment]
An alternative would be to add an `include/nonius.h++` file that includes `include/nonius/nonius.h++`.

**Comment by certik** [comment]
+1, exactly. I have independently written the exact same patch in #21.

**Comment by gnzlbg** [comment]
@certik IIRC there is a related issue here. One should run ninja before with some files before using `nonius` since that fixes this. I don't know why this is this way and I don't recall it being documented anywhere. 

FYI @rmartinho is busy for a couple of weeks but IIRC end of July/beginning of August he should have time to look at these issues and PRs.

**Comment by rmartinho** [comment]
I'm back now and will work through the PRs and issues in the next few days. :D
I'll put this in some document at some point, but can I ask you to send PRs into the `devel` branch instead? If you can edit the PR that would be sweet.

**Comment by gnzlbg** [comment]
Superseeded by #22.

**Pull request closed without merging**
